name: CI 

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig 
        uses: goto-bus-stop/setup-zig@v2
        with: 
          version: 0.11.0

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test

